# SPDX-FileCopyrightText: Copyright (c) 2025 {{ cookiecutter.maintainer_name }} <{{ cookiecutter.maintainer_email }}>
#
# SPDX-License-Identifier: {{ cookiecutter.license }}
---
# Template for individual Docker image configuration.
# Inherits all settings from defaults.yml - only specify what's different.
#
# REQUIRED FIELDS (must customize for each image):
#   - image.name: Unique identifier for this Docker image
#   - image.description: Brief description of image purpose
#   - metadata.license: License for this project (set during project creation)
#
# OPTIONAL OVERRIDES (uncomment to override defaults.yml):
#   - build.platforms: If different from org default
#   - features.*: Enable/disable per image
#   - Any setting from defaults.yml can be overridden here
#
# WORKFLOW:
#   1. Copy this file to a new location
#   2. Update image.name and image.description
#   3. Customize features as needed
#   4. Run: docker run -v $(pwd)/project.yml:/tmp/project.yml ghcr.io/broadsage/scaffold

# Image Identity (REQUIRED - customize for each image)
image:
  name: {{ cookiecutter.project_slug }}
  description: {{ cookiecutter.project_description }}
  version: {{ cookiecutter.image_version }}

# Metadata (REQUIRED - must be set for each project)
metadata:
  license: {{ cookiecutter.license }}

# Template Configuration (tracks template version for updates)
template:
  version: "1.0.0"  # Docker scaffold template version
  source: "https://github.com/broadsage/docker-scaffold"
  protected_files: []  # List files that should not be overwritten during updates
  # - README.md
  # - custom-script.sh

# Override Features (uncomment to change from defaults)
features:
  github: {{ ('true' if cookiecutter.github == 'y' else 'false') | lower }} # Generate GitHub Actions workflow & Issue Templates
  security: {{ ('true' if cookiecutter.security == 'y' else 'false') | lower }} # Enable vulnerability scanning
  registry: {{ ('true' if cookiecutter.registry == 'y' else 'false') | lower }} # Push Docker Images to registries
  compliance: {{ ('true' if cookiecutter.compliance == 'y' else 'false') | lower }} # Enable compliance & code quality tools

# Build Configuration
build:
  architectures:
    - {{ cookiecutter.architectures | default('multi-arch') }}

# Override GitHub Settings (uncomment if needed)
github:
  projects:
    enabled: true
    number: 6
