# SPDX-FileCopyrightText: Copyright (c) 2025 {{ cookiecutter.maintainer_name }} <{{ cookiecutter.maintainer_email }}>
#
# SPDX-License-Identifier: {{ cookiecutter.license }}
---
version: "3"

tasks:
  # Default Task - Show Help
  default:
    desc: Show available tasks
    cmds:
      - task -l

  # Utility Tasks - System & Environment Checks
  docker:
    desc: Verify Docker is installed and available
    cmds:
      - |
        if command -v docker >/dev/null 2>&1; then
          echo "✓ Docker is available"
          docker --version
        else
          echo "✗ Docker is NOT installed"
          exit 1
        fi
    aliases: [verify-docker-installation]

  # Setup Tasks - Environment Initialization
  setup:
    desc: Create Python virtual environment and install dependencies
    status:
      - test -d "{{ cookiecutter._python_venv_dir }}" && test -f "{{ cookiecutter._python_venv_dir }}/pyvenv.cfg" && test -f "{{ cookiecutter._python_venv_dir }}/bin/python3"
    cmds:
      - "python3 -m venv {{ cookiecutter._python_venv_dir }}"
      - |
        source {{ cookiecutter._python_venv_dir }}/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        echo "✓ Virtual environment created and dependencies installed"
    aliases: [init]
    silent: false

  # Quality Checks - Code Quality & Compliance
  lint:
    desc: Run linting checks (MegaLinter)
    deps: [setup]
    cmds:
      - "{{ _python_executable }} scripts/compliance.py lint"

  license:
    desc: |
      Check REUSE license compliance
      Automatically downloads missing licenses before linting
    deps: [setup]
    cmds:
      - "{{ _python_executable}} scripts/compliance.py license"

  conform:
    desc: Validate commits with Conform (direct execution)
    deps: [setup]
    cmds:
      - "{{ _python_executable}} scripts/compliance.py conform"

  compliance:
    desc: Run all code quality & compliance checks
    deps: [setup]
    cmds:
      - "{{ _python_executable}} scripts/compliance.py all"

  generate:
    desc: Generate project files using docker-scaffold container
    deps: [docker]
    cmds:
      - |
        echo "Generating project files using docker-scaffold..."
        docker run --rm \
          -v "$(pwd):/tmp" \
          -e PUID=$(id -u) \
          -e PGID=$(id -g) \
          ghcr.io/broadsage/scaffold:latest
        echo "✓ Project files generated successfully"
        echo "Review generated files in the current directory"

  # Cleanup Tasks - Environment Cleanup
  clean:
    desc: Remove Python virtual environment and cached files
    cmds:
      - |
        if [ -d "{{ cookiecutter._python_venv_dir}}" ]; then
          rm -rf {{ cookiecutter._python_venv_dir }}
          echo "✓ Virtual environment removed"
        else
          echo "⚠ No virtual environment found to clean up"
        fi
      - |
        find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
        find . -type f -name "*.pyc" -delete 2>/dev/null || true
        echo "✓ Cached files cleaned"

  # Workflow Tasks - Complete Workflows
  pipeline:
    desc: Complete CI pipeline (checks, tests, and docker build)
    deps: [generate, compliance]
    cmds:
      - echo "✓ CI pipeline completed successfully"
