# SPDX-FileCopyrightText: Copyright (c) 2025 {{ cookiecutter.maintainer_name }} <{{ cookiecutter.maintainer_email }}>
#
# SPDX-License-Identifier: {{ cookiecutter.license }}
---
version: "3"

tasks:
  # Default Task - Show Help
  default:
    desc: Show available tasks
    cmds:
      - task -l

  # Utility Tasks - System & Environment Checks
  docker:
    desc: Verify Docker is installed and available
    cmds:
      - |
        if command -v docker >/dev/null 2>&1; then
          echo "✓ Docker is available"
          docker --version
        else
          echo "✗ Docker is NOT installed"
          exit 1
        fi
    aliases: [verify-docker-installation]

  # Setup Tasks - Environment Initialization
  setup:
    desc: Create Python virtual environment and install dependencies
    status:
      - test -d "{{ cookiecutter._python_venv_dir }}" && test -f "{{ cookiecutter._python_venv_dir }}/pyvenv.cfg" && test -f "{{ cookiecutter._python_venv_dir }}/bin/python3"
    cmds:
      - "python3 -m venv {{ cookiecutter._python_venv_dir }}"
      - |
        source {{ cookiecutter._python_venv_dir }}/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        echo "✓ Virtual environment created and dependencies installed"
    aliases: [init]
    silent: false

  # Quality Checks - Code Quality & Compliance
  lint:
    desc: Run linting checks (MegaLinter)
    deps: [setup]
    cmds:
      - "{{ cookiecutter._python_executable }} scripts/compliance.py lint"

  license:
    desc: |
      Check REUSE license compliance
      Automatically downloads missing licenses before linting
    deps: [setup]
    cmds:
      - "{{ cookiecutter._python_executable }} scripts/compliance.py license"

  conform:
    desc: Validate commits with Conform (direct execution)
    deps: [setup]
    cmds:
      - "{{ cookiecutter._python_executable }} scripts/compliance.py conform"

  compliance:
    desc: Run all code quality & compliance checks
    deps: [setup]
    cmds:
      - "{{ cookiecutter._python_executable }} scripts/compliance.py all"

  generate:
    desc: Generate project files using docker-scaffold container
    deps: [docker]
    vars:
      VERSION:
        sh: "{{ cookiecutter._python_executable }} scripts/bump_version.py current"
    cmds:
      - |
        echo "Generating project files using docker-scaffold:{{ cookiecutter._template_current_version }}..."
        docker run --rm \
          -v "$(pwd):/tmp" \
          -e PUID=$(id -u) \
          -e PGID=$(id -g) \
          ghcr.io/broadsage/scaffold:{{ cookiecutter._template_current_version }}
        echo "✓ Project files generated successfully"
        echo "Review generated files in the current directory"

  # Template Version Tasks
  template:check:
    desc: Check for template updates (non-destructive)
    aliases: [check-updates]
    deps: [docker]
    cmds:
      - "{{ cookiecutter._python_executable }} scripts/bump_version.py check"

  template:update:
    desc: Update to latest template version (interactive, uses git for safety)
    aliases: [update-template]
    deps: [docker]
    interactive: true
    vars:
      LATEST_VERSION:
        sh: "{{ cookiecutter._python_executable }} scripts/bump_version.py latest"
    cmds:
      # Check git status and warn user
      - |
        if git rev-parse --git-dir > /dev/null 2>&1; then
          if ! git diff-index --quiet HEAD -- 2>/dev/null; then
            echo "⚠️  You have uncommitted changes!"
            echo "It's recommended to commit or stash changes before updating."
            echo ""
            read -p "Continue anyway? (y/N) " -r reply
            if [[ ! $reply =~ ^[Yy]$ ]]; then
              echo "Update cancelled. Commit your changes and try again."
              exit 1
            fi
          fi
        else
          echo "⚠️  Not a git repository!"
          echo "Consider initializing git for safer template updates: git init"
          echo ""
        fi
      # Confirm with user
      - |
        echo "This will regenerate files from the template."
        echo "Protected files in project.yaml will be preserved."
        echo ""
        read -p "Continue? (y/N) " -r reply
        if [[ ! $reply =~ ^[Yy]$ ]]; then
          echo "Update cancelled"
          exit 1
        fi
      # Perform update
      - "{{ cookiecutter._python_executable }} scripts/bump_version.py update"
      - task: generate
      - |
        echo ""
        echo "✓ Template updated to version: {{ cookiecutter._template_latest_version }}"
        echo ""
        if git rev-parse --git-dir > /dev/null 2>&1; then
          echo "Next steps:"
          echo "  1. Review changes: git diff"
          echo "  2. Test changes: task compliance"
          echo "  3. Commit: git add . && git commit -m 'chore: update template to v{{.LATEST_VERSION}}'"
          echo "  4. Rollback if needed: git checkout ."
        else
          echo "Review the changes in your editor"
        fi
          echo "  1. Review changes: git diff"
          echo "  2. Test changes: task compliance"
          echo "  3. Commit: git add . && git commit -m 'chore: update template to v{{ cookiecutter._template_latest_version }}'"
          echo "  4. Rollback if needed: git checkout ."
        else
          echo "Review the changes in your editor"
        fi


  # Cleanup Tasks - Environment Cleanup
  clean:
    desc: Remove Python virtual environment and cached files
    cmds:
      - |
        if [ -d "{{ cookiecutter._python_venv_dir }}" ]; then
          rm -rf {{ cookiecutter._python_venv_dir }}
          echo "✓ Virtual environment removed"
        else
          echo "⚠ No virtual environment found to clean up"
        fi
      - |
        find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
        find . -type f -name "*.pyc" -delete 2>/dev/null || true
        echo "✓ Cached files cleaned"

  # Workflow Tasks - Complete Workflows
  pipeline:
    desc: Complete CI pipeline (checks, tests, and docker build)
    deps: [generate, compliance]
    cmds:
      - echo "✓ CI pipeline completed successfully"
