# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
# Configuration file for MegaLinter using cupcake flavor
# See configuration options at https://oxsecurity.github.io/megalinter/configuration/

# Use cupcake flavor - optimized for Python projects with full linting support
FLAVOR: cupcake

# General
PRINT_ALPACA: false
APPLY_FIXES: all

DISABLE_ERRORS: false
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: false
VALIDATE_ALL_CODEBASE: true

# Reporter options
CLEAR_REPORT_FOLDER: true
EMAIL_REPORTER: false
TEXT_REPORTER: true
SARIF_REPORTER: true
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
GITLAB_COMMENT_REPORTER: false
UPDATED_SOURCES_REPORTER: true

# Exclude directories
EXCLUDE_DIRECTORIES:
  - venv
  - .venv
  - .git
  - .github
  - __pycache__
  - megalinter-reports
  - .ruff_cache

# Enable specific linters
ENABLE_LINTERS:
  # Shell linters
  - BASH_SHELLCHECK
  - BASH_SHFMT
  # Data format linters
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
  # Infrastructure linters
  - DOCKERFILE_HADOLINT
  - ACTION_ACTIONLINT
  # Python linters
  - PYTHON_PYLINT
  - PYTHON_FLAKE8
  - PYTHON_BLACK
  - PYTHON_BANDIT # Security vulnerability detection
  # Repository-wide security scanners
  - REPOSITORY_SECRETLINT # Secret leak detection
  - REPOSITORY_GITLEAKS # Comprehensive secret scanning

# Linter-specific configurations
BASH_SHFMT_ARGUMENTS: -i 2
BASH_SHFMT_FILE_EXTENSIONS: [.sh]
BASH_SHELLCHECK_FILE_EXTENSIONS: [.sh]

MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false

# Exclude cookiecutter template YAML from PRETTIER (keep YAMLLINT validation)
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: .*{{cookiecutter.*
YAML_YAMLLINT_FILE_EXTENSIONS: [.yaml, .yml]

DOCKERFILE_HADOLINT_FILE_EXTENSIONS: [Dockerfile]

PYTHON_PYLINT_FILE_EXTENSIONS: [.py]
PYTHON_FLAKE8_FILE_EXTENSIONS: [.py]
PYTHON_BLACK_FILE_EXTENSIONS: [.py]
