# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0
---
version: "3"

vars:
  PYTHON: python3
  VENV: venv
  PYTHON_VENV: "{{.VENV}}/bin/python3"

tasks:
  # Default Task - Show Help
  default:
    desc: Show available tasks
    cmds:
      - task -l

  # Utility Tasks - System & Environment Checks
  docker:
    desc: Verify Docker is installed and available
    cmds:
      - |
        if command -v docker >/dev/null 2>&1; then
          echo "✓ Docker is available"
          docker --version
        else
          echo "✗ Docker is NOT installed"
          exit 1
        fi
    aliases: [verify-docker-installation]

  # Setup Tasks - Environment Initialization
  setup:
    desc: Create Python virtual environment and install dependencies
    status:
      - test -d "{{.VENV}}" && test -f "{{.VENV}}/pyvenv.cfg" && test -f "{{.VENV}}/bin/python3"
    cmds:
      - "{{.PYTHON}} -m venv {{.VENV}}"
      - |
        source {{.VENV}}/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        echo "✓ Virtual environment created and dependencies installed"
    aliases: [init]
    silent: false

  # Quality Checks - Code Quality & Compliance
  lint:
    desc: Run linting checks (MegaLinter)
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/compliance.py lint"

  publiccode:
    desc: Validate publiccode.yml configuration
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/compliance.py publiccodelint"

  license:
    desc: |
      Check REUSE license compliance
      Automatically downloads missing licenses before linting
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/compliance.py license"

  conform:
    desc: Validate commits with Conform (direct execution)
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/compliance.py conform"

  compliance:
    desc: Run all code quality & compliance checks
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/compliance.py all"

  # Testing - Unit & Integration Tests
  test:
    desc: Run all unit tests
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/test_merge_config.py"

  # Build Tasks - Docker Image Building
  build:
    desc: Build Docker image (broadsage/docker-scaffold:latest)
    deps: [docker]
    cmds:
      - "docker build -t broadsage/docker-scaffold:latest ."
      - echo "✓ Docker image built successfully"

  docker-test:
    desc: Build Docker image and test on current project
    deps: [build]
    cmds:
      - |
        echo "Running docker-scaffold on current project..."
        docker run --rm \
          -v "$(pwd):/tmp" \
          -e PUID=$(id -u) \
          -e PGID=$(id -g) \
          broadsage/docker-scaffold:latest
        echo "✓ Docker container executed successfully"
        echo "Review generated files in the current directory"

  # Cleanup Tasks - Environment Cleanup
  clean:
    desc: Remove Python virtual environment and cached files
    cmds:
      - |
        if [ -d "{{.VENV}}" ]; then
          rm -rf {{.VENV}}
          echo "✓ Virtual environment removed"
        else
          echo "⚠ No virtual environment found to clean up"
        fi
      - |
        find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
        find . -type f -name "*.pyc" -delete 2>/dev/null || true
        echo "✓ Cached files cleaned"

  # Workflow Tasks - Complete Workflows
  validate:
    desc: Validate code quality (checks and tests only, no build)
    deps: [compliance, test]
    cmds:
      - echo "✓ All validation checks passed"

  pipeline:
    desc: Complete CI pipeline (checks, tests, and docker build)
    deps: [compliance, test, build]
    cmds:
      - echo "✓ CI pipeline completed successfully"

  all:
    desc: Complete setup and CI workflow (first-time setup + validation + build)
    deps: [compliance, test, build]
    cmds:
      - echo "✓ All tasks completed successfully"
