# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0
---
version: "3"

vars:
  PYTHON: python3
  VENV: venv
  PYTHON_VENV: "{{.VENV}}/bin/python3"

tasks:
  # Default Task - Show Help
  default:
    desc: Show available tasks
    cmds:
      - task -l

  # Utility Tasks - System & Environment Checks
  check-docker:
    desc: Verify Docker is installed and available
    cmds:
      - |
        if command -v docker >/dev/null 2>&1; then
          echo "✓ Docker is available"
          docker --version
        else
          echo "✗ Docker is NOT installed"
          exit 1
        fi

  # Setup Tasks - Environment Initialization
  setup:
    desc: Create Python virtual environment and install dependencies
    status:
      - test -d "{{.VENV}}" && test -f "{{.VENV}}/pyvenv.cfg"
    cmds:
      - "{{.PYTHON}} -m venv {{.VENV}}"
      - |
        source {{.VENV}}/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        echo "✓ Virtual environment created and dependencies installed"
    aliases: [init]

  # Quality Checks - Code Quality & Compliance
  check-lint:
    desc: Run linting checks (MegaLinter)
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/compliance.py lint"
    aliases: [lint]

  check-publiccode:
    desc: Validate publiccode.yml configuration
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/compliance.py publiccodelint"

  check-license:
    desc: |
      Check REUSE license compliance
      Automatically downloads missing licenses before linting
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/compliance.py license"
    aliases: [license]

  check-commit:
    desc: Validate commit messages with Conform
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/compliance.py commit"
    aliases: [commitlint]

  check-compliance:
    desc: Run all code quality & compliance checks
    deps: [check-lint, check-publiccode, check-license, check-commit]
    cmds:
      - echo "✓ All compliance checks passed"
    aliases: [compliance]

  # Testing - Unit & Integration Tests
  test:
    desc: Run all unit tests
    deps: [setup]
    cmds:
      - "{{.PYTHON_VENV}} scripts/test_merge_config.py"
    aliases: [tests, test-all]

  # Build Tasks - Docker Image Building
  build-docker:
    desc: Build Docker image (broadsage/docker-scaffold:latest)
    deps: [check-docker]
    cmds:
      - "docker build -t broadsage/docker-scaffold:latest ."
      - echo "✓ Docker image built successfully"
    aliases: [build]

  build-and-test:
    desc: Build Docker image and test on current project
    deps: [build-docker]
    cmds:
      - |
        echo "Running docker-scaffold on current project..."
        docker run --rm \
          -v "$(pwd):/tmp" \
          -e PUID=$(id -u) \
          -e PGID=$(id -g) \
          broadsage/docker-scaffold:latest
        echo "✓ Docker container executed successfully"
        echo "Review generated files in the current directory"
    aliases: [docker-run, test-docker]

  # Cleanup Tasks - Environment Cleanup
  clean:
    desc: Remove Python virtual environment and cached files
    cmds:
      - |
        if [ -d "{{.VENV}}" ]; then
          rm -rf {{.VENV}}
          echo "✓ Virtual environment removed"
        else
          echo "⚠ No virtual environment found to clean up"
        fi
      - |
        find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
        find . -type f -name "*.pyc" -delete 2>/dev/null || true
        echo "✓ Cached files cleaned"
    aliases: [cleanup]

  # Workflow Tasks - Complete Workflows
  validate:
    desc: Validate code quality (checks and tests only, no build)
    deps: [setup, check-compliance, test]
    cmds:
      - echo "✓ All validation checks passed"
    aliases: [verify]

  pipeline:
    desc: Complete CI pipeline (checks, tests, and docker build)
    deps: [check-compliance, test, build-docker]
    cmds:
      - echo "✓ CI pipeline completed successfully"
    aliases: [ci]

  all:
    desc: Complete setup and CI workflow (first-time setup + validation + build)
    deps: [check-compliance, test, build-docker]
    cmds:
      - echo "✓ All tasks completed successfully"
