#
# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage
# SPDX-License-Identifier: Apache-2.0
#

title: "📢 [Announcement]: "
labels: ["announcement", "news"]
body:
  - type: markdown
    attributes:
      value: |
        Share important news with the community! 📢

        Use this template for project announcements, releases, updates, or important information that affects all users.

  - type: textarea
    id: announcement-title
    attributes:
      label: Announcement Title
      description: Clear, concise title for this announcement
      placeholder: "e.g., Release: v2.0 with multi-platform support"
    validations:
      required: true

  - type: textarea
    id: announcement-content
    attributes:
      label: Announcement Content
      description: Detailed announcement information
      placeholder: |
        ### Summary
        Brief overview

        ### Key Points
        - Point 1
        - Point 2
        - Point 3

        ### Impact
        How does this affect users?

        ### Resources
        - Link to documentation
        - Link to migration guide
      validations:
        required: true

  - type: dropdown
    id: announcement-type
    attributes:
      label: Announcement Type
      description: What category is this announcement?
      options:
        - Release / Version Update
        - Security Update
        - Breaking Changes
        - Feature Launch
        - Maintenance Window
        - Policy Change
        - Other
      validations:
        required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How urgent is this announcement?
      options:
        - Critical - Immediate action required
        - High - Important for all users
        - Medium - Good to know
        - Low - FYI
      validations:
        required: true

  - type: textarea
    id: action-required
    attributes:
      label: Action Required (if any)
      description: Do users need to take any action?
      placeholder: "Leave blank if no action needed"

  - type: textarea
    id: references
    attributes:
      label: Related Links
      description: Links to documentation, issues, PRs, or other resources
      placeholder: |
        - GitHub Release: https://github.com/...
        - Documentation: https://...
        - Migration Guide: https://...
