# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0
---
labels: ["announcement", "news"]
body:
  - type: markdown
    attributes:
      value: |
        # 📣 Project Announcement

        **Welcome to our community!** We're excited to hear your important updates and news.

        Share your thoughts freely—this is a space for you to announce project news, releases, and important information that matters to everyone.

        ## Best practices for announcements
        - **Be clear and concise** about what's new
        - **Highlight impact** so people understand why it matters
        - **Provide links** to documentation or resources
        - **Set expectations** for timelines and next steps
        - **Engage respectfully** with community feedback

  - type: textarea
    id: announcement-summary
    attributes:
      label: Announcement Summary
      description: What is this announcement about?
      placeholder: "Please provide a brief summary of this announcement"
    validations:
      required: true

  - type: textarea
    id: announcement-details
    attributes:
      label: Announcement Details
      description: Provide detailed information about this announcement
      placeholder: "Describe the announcement, why it matters, and any next steps"

  - type: textarea
    id: announcement-links
    attributes:
      label: Related Resources
      description: Links to documentation, guides, or other resources
      placeholder: "Share relevant links: documentation, release notes, blog posts, etc."
