---
labels: ["announcement", "news"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to announcements! 📢

        Use this to share important news, releases, updates, or information that affects all users.
        Our community stays informed about project developments here.

  - type: textarea
    id: announcement-summary
    attributes:
      label: Announcement Summary
      description: What is this announcement about?
      placeholder: "Please provide a brief summary of this announcement"
    validations:
      required: true

  - type: textarea
    id: announcement-details
    attributes:
      label: Announcement Details
      description: Provide detailed information about this announcement
      placeholder: "Describe the announcement, why it matters, and any next steps"

  - type: textarea
    id: announcement-links
    attributes:
      label: Related Resources
      description: Links to documentation, guides, or other resources
      placeholder: "Share relevant links: documentation, release notes, blog posts, etc."
