title: Get Help & Support
body:
  - type: markdown
    attributes:
      value: |
        # 🆘 Get Help

        Welcome to the docker-scaffold community support discussion!
        
        Please provide detailed information to help us assist you better.

  - type: textarea
    id: issue-description
    attributes:
      label: What are you trying to do?
      description: Describe your use case and what you're trying to accomplish
      placeholder: |
        I'm trying to scaffold a Docker image for...
      validations:
        required: true

  - type: textarea
    id: steps-taken
    attributes:
      label: Steps You've Already Tried
      description: What troubleshooting have you already done?
      placeholder: |
        - I tried...
        - I checked...
        - I searched for...
      validations:
        required: true

  - type: textarea
    id: environment
    attributes:
      label: Your Environment
      description: Help us understand your setup
      value: |
        - docker-scaffold version: [e.g., 1.0.0]
        - Docker version: [e.g., 24.0.0]
        - OS: [e.g., macOS 13.0, Ubuntu 22.04]
        - Shell: [e.g., bash, zsh]
      validations:
        required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages or Logs
      description: Please share any error messages or relevant log output
      render: bash
      placeholder: |
        Paste error output here...

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What should happen instead?
      placeholder: |
        When I run the command, it should...
      validations:
        required: true

  - type: checkboxes
    id: resources-checked
    attributes:
      label: Resources Checked
      description: Have you checked these resources?
      options:
        - label: README and documentation
        - label: Existing discussions and issues
        - label: Troubleshooting guide (if available)
        - label: Recent changelog

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help?
      placeholder: "Configuration file excerpts, screenshots, etc."
