---
labels: ["help", "question"]
body:
  - type: markdown
    attributes:
      value: |
        # ❓ Need Help?

        **Welcome to our community support space!** We're here to help you succeed with this project.

        Share your questions openly—no question is too small. Our community loves helping each other, and your question might help others too.

        ## Best practices for asking questions
        - **Be specific** about what you're trying to do
        - **Share error messages** and relevant logs
        - **Describe what you've already tried** to solve it
        - **Include your environment details** (OS, versions, etc.)
        - **Be patient and appreciative** with those who help

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like help with?
      placeholder: "Please describe your question or the issue you're encountering"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide more context about your situation
      placeholder: "What were you trying to do? What's your use case?"

  - type: textarea
    id: steps-taken
    attributes:
      label: Steps You've Already Tried
      description: What have you already tried to solve this?
      placeholder: "Describe the steps you've already taken"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Share relevant environment details
      value: "OS: [macOS/Linux/Windows], Version: [e.g., 1.0.0], Docker version: [e.g., 24.0]"

  - type: textarea
    id: error-output
    attributes:
      label: Error Messages or Output
      description: If applicable, share any error messages or relevant output
      render: bash
      placeholder: "Paste error output or logs here"

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that might help?
      placeholder: "Code snippets, configuration files, screenshots, etc."
