---
title: "❓ Help"
labels: ["help", "question"]
body:
  - type: markdown
    attributes:
      value: |
        # ❓ Need Help?

        Got a question or need assistance? Please provide:
        - What are you trying to do?
        - What have you already tried?
        - What's your environment (OS, Docker version, etc)?
        - Any error messages or output?
