title: Share Ideas & Feedback
body:
  - type: markdown
    attributes:
      value: |
        # 💡 Ideas & Feedback

        Have a suggestion to improve docker-scaffold? We'd love to hear from you!
        
        This space is for sharing ideas, gathering feedback, and discussing potential improvements to the project.

  - type: textarea
    id: idea-summary
    attributes:
      label: Idea Summary
      description: Give your idea a concise title and summary
      placeholder: |
        Add support for multi-stage builds with automatic layer optimization
      validations:
        required: true

  - type: textarea
    id: idea-description
    attributes:
      label: Detailed Description
      description: Explain your idea in detail. Why would this improve docker-scaffold?
      placeholder: |
        ### Problem
        Currently, scaffolding large Docker images takes a long time because...

        ### Proposed Solution
        We could implement...

        ### Benefits
        - Faster build times
        - Reduced image sizes
        - Better developer experience
      validations:
        required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: What specific use cases would this help with?
      placeholder: |
        - Developers building complex microservices
        - Teams with CI/CD pipelines
        - Organizations standardizing Docker practices
      validations:
        required: true

  - type: dropdown
    id: impact-area
    attributes:
      label: What area does this affect?
      description: Select the primary area impacted by this idea
      options:
        - Performance & Speed
        - Developer Experience
        - Security Features
        - Documentation & Learning
        - Compatibility & Integration
        - Community & Governance
      validations:
        required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or approaches did you consider?
      placeholder: |
        - Alternative 1: We could...
        - Alternative 2: Another approach might be...
        - Why the proposed solution is better...

  - type: checkboxes
    id: community-interest
    attributes:
      label: Community Interest
      description: Help us gauge community interest
      options:
        - label: I would help implement this feature
        - label: I would test and provide feedback
        - label: This solves a real problem I have
        - label: I'd like to see this prioritized

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Links to issues, discussions, or resources related to this idea
      placeholder: "Closes #123, Related to discussion #456"
