---
labels: ["poll", "community-input"]
body:
  - type: markdown
    attributes:
      value: |
        # 🗳️ Community Poll

        **Welcome! Let's make decisions together.** Your vote and input shape what we build next.

        Create a poll to gather community input on important decisions. This is where we all have a voice in guiding the project forward.

        ## Best practices for polls
        - **Ask one clear question** at a time
        - **Provide sufficient context** so people understand what they're voting on
        - **Offer distinct options** that represent meaningful choices
        - **Set a voting deadline** so we can move forward
        - **Share results and next steps** with the community

  - type: textarea
    id: poll-question
    attributes:
      label: Poll Question
      description: What question are you asking the community?
      placeholder: "Clear, specific question for the community to vote on"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context and Background
      description: Provide context to help community members make informed decisions
      placeholder: "Why is this poll needed? What's the background information?"
    validations:
      required: true

  - type: textarea
    id: options
    attributes:
      label: Poll Options
      description: List the available options or use reaction emojis
      placeholder: "List voting options or use: 👍 for Yes, 👎 for No, 🤔 for Maybe"
    validations:
      required: true

  - type: textarea
    id: criteria
    attributes:
      label: Decision Criteria
      description: What factors should people consider when voting?
      placeholder: "What criteria or considerations should influence the decision?"

  - type: input
    id: deadline
    attributes:
      label: Poll Deadline
      description: When should voting close?
      placeholder: "e.g., 2025-09-15 or 'one week from now'"

  - type: textarea
    id: impact
    attributes:
      label: Impact of Decision
      description: How will the poll results be used?
      placeholder: "Describe how this decision will affect the project"
