#!/usr/bin/env python3
"""Post-generation hook for cookiecutter template.

This hook runs AFTER project.yaml and Taskfile.yml are generated.
Displays next steps for using the Docker scaffold image to generate the full project.

No file manipulation happens here - everything else is generated by running:
    task generate
    
Which uses the Docker image containing all Ansible templates.
"""

import sys


def display_next_steps() -> None:
    """Display instructions for completing project setup."""
    project_slug = '{{ cookiecutter._project_slug }}'
    organization = '{{ cookiecutter.organization }}'
    scaffold_image = '{{ cookiecutter.scaffold_image }}'
    
    print("\n" + "=" * 70)
    print(f"✅ Project '{project_slug}' initialized successfully!")
    print("=" * 70)
    
    print("\n📦 Generated Files:")
    print(f"  ✓ {project_slug}/project.yaml     - Project configuration")
    print(f"  ✓ {project_slug}/Taskfile.yml     - Task automation")
    print(f"  ✓ {project_slug}/README.md        - Quick start guide")
    print(f"  ✓ {project_slug}/.gitignore       - Git ignore patterns")
    
    print("\n🚀 Next Steps:")
    print(f"\n  1️⃣  Enter your project directory:")
    print(f"      cd {project_slug}")
    
    print("\n  2️⃣  Generate full project structure using Docker:")
    print("      task generate")
    print(f"      # Runs: docker run --rm -v $(pwd):/output {scaffold_image}")
    
    print("\n  3️⃣  Review generated files:")
    print("      ls -la")
    print("      # You'll see: Dockerfile, .github/, .conform.yaml, etc.")
    
    print("\n  4️⃣  Build your Docker image:")
    print("      task build")
    
    print("\n  5️⃣  Run compliance checks:")
    print("      task compliance")
    
    print("\n  6️⃣  (Optional) Initialize Git repository:")
    print("      git init")
    print("      git add .")
    print('      git commit -s -m "feat: initialize project from scaffold"')
    print(f"      git remote add origin https://github.com/{organization}/{project_slug}.git")
    print("      git push -u origin main")
    
    print("\n📚 Documentation:")
    print("  • README.md         - Project overview and setup")
    print("  • Taskfile.yml      - Available tasks (run 'task -l')")
    print("  • project.yaml      - Customize features and settings")
    
    print("\n💡 Tips:")
    print("  • Edit project.yaml to enable/disable features")
    print("  • Run 'task generate' again after changing project.yaml")
    print("  • Use 'task -l' to see all available tasks")
    print(f"  • Update templates: docker pull {scaffold_image}")
    
    print("\n" + "=" * 70)
    print("Need help? https://github.com/broadsage/docker-scaffold/discussions")
    print("=" * 70 + "\n")


def main() -> None:
    """Run post-generation tasks."""
    try:
        display_next_steps()
    except Exception as e:
        print(f"\n❌ Error: {e}", file=sys.stderr)
        print("   Project was created but post-generation display failed.")
        sys.exit(1)


if __name__ == '__main__':
    main()
