#!/usr/bin/env python3
"""Post-generation hook for cookiecutter template.

This hook runs AFTER project.yaml and Taskfile.yml are generated.
Displays progress events for completing project setup.

No file manipulation happens here - everything else is generated by running:
    task generate

Which uses the Docker image containing all Ansible templates.
"""

import sys
from datetime import datetime


def get_timestamp() -> str:
    """Get current time in HH:MM:SS format."""
    return datetime.now().strftime("%H:%M:%S")


def print_event(emoji: str, message: str) -> None:
    """Print formatted event message with timestamp."""
    timestamp = get_timestamp()
    print(f"{emoji} {message} • {timestamp}")


def display_next_steps() -> None:
    """Display instructions for completing project setup."""
    project_slug = "{{ cookiecutter.project_slug }}"
    organization = "{{ cookiecutter.organization }}"
    scaffold_image = "{{ cookiecutter.scaffold_image }}"

    print()
    print_event("✅", f"Project '{project_slug}' initialized successfully")
    print_event("📦", "Generated: project.yaml, Taskfile.yml, README.md, .gitignore")
    print_event("📝", f"Configuration: {project_slug}/project.yaml")
    print()
    print_event("🚀", "Next Steps:")
    print()
    print(f"  1. cd {project_slug}")
    print(f"  2. task generate           # Generate full project with Docker")
    print(f"  3. task build              # Build Docker image")
    print(f"  4. task compliance         # Run code quality checks")
    print()
    print_event("💡", "Customize: Edit project.yaml and run 'task generate' again")
    print_event("❓", "Help: https://github.com/broadsage/docker-scaffold/discussions")
    print_event("📚", "Docs: https://github.com/broadsage/docker-scaffold/blob/main/README.md")
    print()


def main() -> None:
    """Run post-generation tasks."""
    try:
        display_next_steps()
    except Exception as e:
        print(f"\n❌ Error: {e}", file=sys.stderr)
        print("   Project was created but post-generation display failed.")
        sys.exit(1)


if __name__ == "__main__":
    main()
